//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStore.Business.Components.DeliveryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeliveryService.IDeliveryService")]
    public interface IDeliveryService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDeliveryService/SubmitDelivery")]
        void SubmitDelivery(DeliveryCo.MessageTypes.DeliveryInfo pDeliveryInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDeliveryService/SubmitDelivery")]
        System.Threading.Tasks.Task SubmitDeliveryAsync(DeliveryCo.MessageTypes.DeliveryInfo pDeliveryInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeliveryServiceChannel : VideoStore.Business.Components.DeliveryService.IDeliveryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeliveryServiceClient : System.ServiceModel.ClientBase<VideoStore.Business.Components.DeliveryService.IDeliveryService>, VideoStore.Business.Components.DeliveryService.IDeliveryService {
        
        public DeliveryServiceClient() {
        }
        
        public DeliveryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeliveryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeliveryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeliveryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SubmitDelivery(DeliveryCo.MessageTypes.DeliveryInfo pDeliveryInfo) {
            base.Channel.SubmitDelivery(pDeliveryInfo);
        }
        
        public System.Threading.Tasks.Task SubmitDeliveryAsync(DeliveryCo.MessageTypes.DeliveryInfo pDeliveryInfo) {
            return base.Channel.SubmitDeliveryAsync(pDeliveryInfo);
        }
    }
}
